### ISSUE TITLE
if image-challenge-popup already exists, calling solveCaptcha will click checkbox again, therefore making image challenge disappear

### ISSUE THREAD

**Issue by leanderhamzoui** [noCaptchaAi/nocaptchaai-puppeteer#2]
if image-challenge-popup already exists, calling solveCaptcha will click checkbox again, therefore making image challenge disappear
i myself use solveCaptcha only if imagechallenge exists. also necessary for invisible captcha because there is no checkbox to be clicked. 

Suggested Solution:

check if image challenge already exists or not. if not, click checkbox.

    var challengecheck = (await innerFrame.evaluate(()=>document.querySelector("body .challenge"))) || "";
    if (!challengecheck) {
    await checkbox?.click();
    }

**Comment by 404b** [comment]
Can you still re-produce this?
