### ISSUE TITLE
target innerframe correctly

### ISSUE THREAD

**Issue by leanderhamzoui** [noCaptchaAi/nocaptchaai-puppeteer#3]
otherwise its not working for me on my site, also this way is more correct:

    //const inner = await page.waitForSelector('iframe:not([data-hcaptcha-response])');
    const inner = await page.$("iframe[title='Main content of the hCaptcha challenge']",);

**Comment by MoKhajavi75** [comment]
What's the site?

**Comment by 404b** [comment]
> otherwise its not working for me on my site, also this way is more correct:
> 
> ```
> //const inner = await page.waitForSelector('iframe:not([data-hcaptcha-response])');
> const inner = await page.$("iframe[title='Main content of the hCaptcha challenge']",);
> ```

fixed. thanks for report.
