### ISSUE TITLE
language not detected

### ISSUE THREAD

**Issue by leanderhamzoui** [noCaptchaAi/nocaptchaai-puppeteer#4]
this aint working

        const language = await page.evaluate(() => document.documentElement.lang);

console.log(language) returns empty

**Comment by MoKhajavi75** [comment]
What's the site?

**Comment by 404b** [comment]
> this aint working
> 
> ```
>     const language = await page.evaluate(() => document.documentElement.lang);
> ```
> 
> console.log(language) returns empty

Language detection is fixed. You can open this issue again if this not solves for you.
